### ISSUE TITLE
Todo list (for new releases)

### ISSUE THREAD

**Issue by DanielRuf** [stefanjudis/forrest#125]
- [ ] extend Node.js CI matrix (6, 8, 10, latest)
- [ ] update dependencies
- [ ] migrate code
- [ ] add Windows and macOS to CI matrix
- [ ] write some tests with Jest

**Comment by stefanjudis** [comment]
This looks great! Tiny comment. :)

> extend Node.js CI matrix (6, 8, 10, latest)

I don't think we need a matrix for this. :) For unit tests (on the main process) the node version that electron bundles (currently `v10`) should work fine. :)

**Comment by DanielRuf** [comment]
How can we assure then that the whole project works on 6 and up (also for contributors)?

**Comment by stefanjudis** [comment]
Hmm... but when you're testing code that runs in electron in node 10 wouldn't it be a good idea to make node 10 mandatory to run tests in the same env as the electron process?

I'm not strictly against it but I'd vote for node 10 as min node version because it comes with electron. :)

**Comment by DanielRuf** [comment]
It only makes sense when we upgrade the electron dependency which might introduce a *few* breaking changes. Electron itself is an encapsulated environment but does not affect the build tools / dev dependencies.

But we'll see then what the best strategy will be (like adding allowed failures to the CI setup and slowly upgrading all dependencies).
